from sqlalchemy import Column, String, Integer, DateTime
from app.database.db import Base
from uuid import uuid4

class Subscription(Base):
    __tablename__ = "subscriptions"

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    user_id = Column(String, index=True)
    payment_provider = Column(String, default="nowpayments")
    crypto_payment_id = Column(String, index=True, nullable=True) # Payment ID generated by NOWPayments
    crypto_tx_hash = Column(String, unique=True, index=True, nullable=True) # Hash on the blockchain
    payment_currency = Column(String, default="usdt") # Currency user paid with
    plan = Column(String)
    status = Column(String)
    current_period_end = Column(DateTime)
