"""Add OAuthAccount table and decouple OAuth from User

Revision ID: 0aa06c114146
Revises: a2b3c4d5e6f7
Create Date: 2026-03-16 23:51:34.535341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa06c114146'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'APPLE', 'GITHUB', 'DISCORD', name='authprovider'), nullable=False),
    sa.Column('provider_sub', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('provider_avatar', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_sub', name='uix_provider_sub')
    )
    op.create_index(op.f('ix_oauth_accounts_provider_email'), 'oauth_accounts', ['provider_email'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.alter_column('bots', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.alter_column('bots', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bots', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bots', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bots', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bots', 'max_lot_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.01'))
    op.alter_column('bots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('bots_slug_key'), 'bots', type_='unique')
    op.create_index(op.f('ix_bots_slug'), 'bots', ['slug'], unique=True)
    op.alter_column('positions', 'bot_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('trades', 'bot_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_bots', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.alter_column('user_bots', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_bots', 'bot_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_bots', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('user_bots_user_id_bot_id_key'), 'user_bots', type_='unique')
    op.create_index(op.f('ix_user_bots_bot_id'), 'user_bots', ['bot_id'], unique=False)
    op.create_index(op.f('ix_user_bots_user_id'), 'user_bots', ['user_id'], unique=False)
    op.create_unique_constraint('uix_user_bot', 'user_bots', ['user_id', 'bot_id'])
    op.drop_constraint(op.f('user_bots_bot_id_fkey'), 'user_bots', type_='foreignkey')
    op.drop_constraint(op.f('user_bots_user_id_fkey'), 'user_bots', type_='foreignkey')
    op.create_foreign_key(None, 'user_bots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bots', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'mt_password_enc',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'mt_password_enc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'email_verified')
    op.drop_constraint(None, 'user_bots', type_='foreignkey')
    op.drop_constraint(None, 'user_bots', type_='foreignkey')
    op.create_foreign_key(op.f('user_bots_user_id_fkey'), 'user_bots', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_bots_bot_id_fkey'), 'user_bots', 'bots', ['bot_id'], ['id'])
    op.drop_constraint('uix_user_bot', 'user_bots', type_='unique')
    op.drop_index(op.f('ix_user_bots_user_id'), table_name='user_bots')
    op.drop_index(op.f('ix_user_bots_bot_id'), table_name='user_bots')
    op.create_unique_constraint(op.f('user_bots_user_id_bot_id_key'), 'user_bots', ['user_id', 'bot_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_bots', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_bots', 'bot_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_bots', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_bots', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.alter_column('trades', 'bot_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('positions', 'bot_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bots_slug'), table_name='bots')
    op.create_unique_constraint(op.f('bots_slug_key'), 'bots', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('bots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('bots', 'max_lot_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.01'))
    op.alter_column('bots', 'symbol',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bots', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bots', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bots', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bots', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_provider_email'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
