"""Add exchange_api_key and exchange_secret_key to Users for Binance credentials

Revision ID: 52a10d3f4e8b
Revises: 7d160d3f4e8a
Create Date: 2026-03-08 17:39:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a10d3f4e8b'
down_revision: Union[str, Sequence[str], None] = '7d160d3f4e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exchange_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('exchange_secret_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exchange_secret_key')
    op.drop_column('users', 'exchange_api_key')
    # ### end Alembic commands ###
