"""Add meta_account_id to Users

Revision ID: 7d160d3f4e8a
Revises: e2f34340fd21
Create Date: 2026-03-08 11:18:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d160d3f4e8a'
down_revision: Union[str, Sequence[str], None] = 'e2f34340fd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('meta_account_id', sa.String(), nullable=True))
    op.create_index('ix_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.drop_constraint('subscriptions_stripe_subscription_id_key', 'subscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subscriptions_stripe_subscription_id_key', 'subscriptions', ['stripe_subscription_id'])
    op.drop_index('ix_subscriptions_stripe_subscription_id', table_name='subscriptions')
    op.drop_column('users', 'meta_account_id')
    # ### end Alembic commands ###
