"""Add mt5 balance to users

Revision ID: c6ecbb5e618b
Revises: 8f2c1b2c3d4e
Create Date: 2026-03-09 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ecbb5e618b'
down_revision = '8f2c1b2c3d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mt5_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('mt5_equity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mt5_equity')
    op.drop_column('users', 'mt5_balance')
    # ### end Alembic commands ###
