"""Add signal tracking schema

Revision ID: e144f41bdd28
Revises: 0aa06c114146
Create Date: 2026-03-17 12:21:10.986622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e144f41bdd28'
down_revision: Union[str, Sequence[str], None] = '0aa06c114146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('lot_size', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('unrealized_pnl', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('metaapi_position_id', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('opened_at', sa.DateTime(), nullable=True))
    op.add_column('positions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'positions', 'users', ['user_id'], ['id'])
    op.add_column('signals', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('bot_id', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('direction', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('signal_time', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('price_at_signal', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('signals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('signals', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_signals_user_id'), 'signals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'signals', 'bots', ['bot_id'], ['id'])
    op.create_foreign_key(None, 'signals', 'users', ['user_id'], ['id'])
    op.drop_column('signals', 'action')
    op.drop_column('signals', 'price')
    op.add_column('trades', sa.Column('signal_id', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('lot_size', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('execution_time', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('close_time', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('execution_latency_ms', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('status', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('metaapi_trade_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_trades_execution_time'), 'trades', ['execution_time'], unique=False)
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_foreign_key(None, 'trades', 'signals', ['signal_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'])
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'uq_users_oauth_sub'
            ) THEN
                ALTER TABLE users DROP CONSTRAINT uq_users_oauth_sub;
            END IF;
        END $$;
        """
    )
    op.drop_column('users', 'oauth_sub')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('oauth_sub', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_users_oauth_sub'), 'users', ['oauth_sub'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_execution_time'), table_name='trades')
    op.drop_column('trades', 'metaapi_trade_id')
    op.drop_column('trades', 'status')
    op.drop_column('trades', 'execution_latency_ms')
    op.drop_column('trades', 'close_time')
    op.drop_column('trades', 'execution_time')
    op.drop_column('trades', 'lot_size')
    op.drop_column('trades', 'signal_id')
    op.add_column('signals', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_index(op.f('ix_signals_user_id'), table_name='signals')
    op.alter_column('signals', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('signals', 'created_at')
    op.drop_column('signals', 'raw_payload')
    op.drop_column('signals', 'price_at_signal')
    op.drop_column('signals', 'signal_time')
    op.drop_column('signals', 'direction')
    op.drop_column('signals', 'bot_id')
    op.drop_column('signals', 'user_id')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_column('positions', 'updated_at')
    op.drop_column('positions', 'opened_at')
    op.drop_column('positions', 'metaapi_position_id')
    op.drop_column('positions', 'unrealized_pnl')
    op.drop_column('positions', 'current_price')
    op.drop_column('positions', 'lot_size')
    # ### end Alembic commands ###
