"""add_trade_reject_reason

Revision ID: e9b709bcdad6
Revises: e144f41bdd28
Create Date: 2026-03-17 12:46:23.467399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b709bcdad6'
down_revision: Union[str, Sequence[str], None] = 'e144f41bdd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('reject_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'reject_reason')
    # ### end Alembic commands ###
